---
- name: Check if cursor command exists
  ansible.builtin.command: which cursor
  register: cursor_check
  ignore_errors: yes
  changed_when: false

- name: Create Cursor directory
  become: yes
  ansible.builtin.file:
    path: /opt/cursor
    state: directory
    mode: '0755'
  when: cursor_check.rc != 0

- name: Download Cursor AppImage
  become: yes
  ansible.builtin.get_url:
    url: "https://downloads.cursor.com/production/031e7e0ff1e2eda9c1a0f5df67d44053b059c5df/linux/x64/Cursor-1.2.1-x86_64.AppImage"
    dest: "/opt/cursor/cursor.bin"
    mode: '0755'
  when: cursor_check.rc != 0

- name: Create cursor.bin symlink in /usr/local/bin
  become: yes
  ansible.builtin.file:
    src: "/opt/cursor/cursor.bin"
    dest: "/usr/local/bin/cursor.bin"
    state: link
  when: cursor_check.rc != 0

- name: Create cursor launcher script
  become: yes
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      /opt/cursor/cursor.bin --no-sandbox "$@"
    dest: "/usr/local/bin/cursor-launcher"
    mode: '0755'
  when: cursor_check.rc != 0

- name: Create cursor symlink for launcher
  become: yes
  ansible.builtin.file:
    src: "/usr/local/bin/cursor-launcher"
    dest: "/usr/local/bin/cursor"
    state: link
  when: cursor_check.rc != 0 
