---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - cursor
    - jetbrains-toolbox
    - repos
  tasks:

    - name: Add ssh_config Include directive to ~/.ssh/config
      become: no
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.ssh/config"
        line: "Include {{ git_dir }}/authorized-keys/ssh_config"
        state: present
        create: yes
        mode: '0600'
      tags: ssh

    - name: Create ssh directory in authorized-keys
      become: no
      ansible.builtin.file:
        path: "{{ git_dir }}/authorized-keys/ssh"
        state: directory
        mode: '0700'
      tags: ssh

    - name: Create symbolic link for personal ssh key
      become: no
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/.ssh/id_rsa"
        dest: "{{ ansible_env.HOME }}/.ssh/id_infra"
        state: link
        force: yes
      tags: ssh

    - name: Add local.songsterr.dev entries to /etc/hosts
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "127.0.0.1 local.songsterr.dev local-static.songsterr.dev"
        - "::1 local.songsterr.dev local-static.songsterr.dev"
      tags: web

    - name: Allow Node.js to use ports below 1024
      become: yes
      ansible.builtin.command: setcap 'cap_net_bind_service=+ep' /usr/local/bin/node
      args:
        creates: /usr/local/bin/node
      tags: web
