---
- hosts: localhost
  vars_files:
    - vars.yml
  vars:
    git_dir: "/home/{{ my_user }}/git"
    repos:
      - name: "songsterr-web"
        url: "git@github.com:songsterr/songsterr-web.git"
      - name: "render-server-satellite"
        url: "git@github.com:songsterr/render-server-satellite.git"
      - name: "midi-generator"
        url: "git@github.com:songsterr/midi-generator.git"
  tasks:
    - name: Ensure git directory exists
      become: no
      ansible.builtin.file:
        path: "{{ git_dir }}"
        state: directory
        owner: "{{ my_user }}"
        group: "{{ my_group }}"
        mode: '0755'

    - name: Clone repositories
      become: no
      ansible.builtin.git:
        repo: "{{ item.url }}"
        dest: "{{ git_dir }}/{{ item.name }}"
        accept_hostkey: yes
        key_file: "/home/{{ my_user }}/.ssh/id_rsa"
        update: yes
      environment:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      loop: "{{ repos }}" 