---
- hosts: localhost
  vars_files:
    - vars.yml
  vars:
    git_dir: "/home/{{ my_user }}/git"
    repos:
      - name: "songsterr-web"
        url: "git@github.com:songsterr/songsterr-web.git"
      - name: "render-server-satellite"
        url: "git@github.com:songsterr/render-server-satellite.git"
      - name: "midi-generator"
        url: "git@github.com:songsterr/midi-generator.git"
      - name: "render-server"
        url: "git@github.com:songsterr/RenderServer.git"
      - name: "songsterr-infra"
        url: "git@github.com:songsterr/songsterr-infra.git"
      - name: "processor-json"
        url: "git@github.com:songsterr/songsterr-processor-json.git"
      - name: "songsterr-openapi"
        url: "git@github.com:songsterr/songsterr-openapi.git"
      - name: "songsterr-auth"
        url: "git@github.com:songsterr/songsterr-auth.git"
      - name: "temporal-worker"
        url: "git@github.com:songsterr/temporal-worker.git"
      - name: "songsterr-conductor"
        url: "git@github.com:songsterr/songsterr-conductor.git"
      - name: "opentelemetry-ts-instrumentation"
        url: "git@github.com:songsterr/opentelemetry-ts-instrumentationworker.git"
  tasks:
    - name: Ensure git directory exists
      become: no
      ansible.builtin.file:
        path: "{{ git_dir }}"
        state: directory
        owner: "{{ my_user }}"
        group: "{{ my_group }}"
        mode: '0755'

    - name: Clone repositories
      become: no
      ansible.builtin.git:
        repo: "{{ item.url }}"
        dest: "{{ git_dir }}/{{ item.name }}"
        accept_hostkey: yes
        key_file: "/home/{{ my_user }}/.ssh/id_rsa"
        update: yes
      environment:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      loop: "{{ repos }}" 