---
- hosts: localhost
  vars_files:
    - vars.yml
  vars:
    my_group: "{{ ansible_user_gid }}"
  roles:
    - vpn
    - docker
    - nodejs
  tasks:
    - name: Ensure SSH directory exists
      become: no
      ansible.builtin.file:
        path: "/home/{{ my_user }}/.ssh"
        state: directory
        owner: "{{ my_user }}"
        group: "{{ my_user }}"
        mode: '0700'

    - name: Check if SSH key already exists
      stat:
        path: "/home/{{ my_user }}/.ssh/id_rsa"
      register: ssh_key

    - name: Generate OpenSSH keypair
      become: no
      openssh_keypair:
        path: "/home/{{ my_user }}/.ssh/id_rsa"
        type: rsa
        size: 4096
        owner: "{{ my_user }}"
        group: "{{ my_user }}"
      when: not ssh_key.stat.exists

    - name: Fix OpenSSH access rights
      become: yes
      file:
        path: "/home/{{ my_user }}/.ssh/id_rsa.pub"
        owner: "{{ my_user }}"
        group: "{{ my_user }}"
        mode: '0644'

    - name: Configure Git user email
      become: yes
      ansible.builtin.git_config:
        name: user.email
        value: "{{ git_user_email }}"
        scope: system

    - name: Configure Git user name
      become: yes
      ansible.builtin.git_config:
        name: user.name
        value: "{{ git_user_name }}"
        scope: system

    - name: Ensure user's local bin directory exists
      become: no
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: '0755'

    - name: Add ~/.local/bin to PATH in .bashrc
      become: no
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH="$HOME/.local/bin:$PATH"'
        state: present

    - name: Add Chrome key
      become: yes
      ansible.builtin.apt_key:
        url: "https://dl.google.com/linux/linux_signing_key.pub"
        state: present

    - name: Add Chrome repo
      become: yes
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome

    - name: Install core packages
      become: yes
      apt:
        pkg:
          - mc
          - net-tools
          - wget
          - openssh-server
          - git
          - apt-transport-https
          - google-chrome-stable
          - libfuse2
          - ntfs-3g
          - vlc
          - ffmpeg
          - lame
          - sox
          - xclip
          - openjdk-21-jdk
          - libnss3-tools
          - dos2unix
          - ecryptfs-utils
          - cryptsetup
          - shadowsocks-libev
        state: latest
        update_cache: true

    # https://1password.com/ru/downloads/linux/
    # https://stackoverflow.com/questions/41271525/ansible-installation-of-debian-packages
    - name: Install 1P
      become: yes
      apt:
        deb: "https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb"

    - name: Open SSH port
      become: yes
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Install Nomad via snap
      become: yes
      community.general.snap:
        name: nomad
        state: present
        classic: yes
      tags: nomad

    - name: Install Vault via snap
      become: yes
      community.general.snap:
        name: vault
        state: present
        classic: yes
      tags: nomad

    - name: Install Go via snap
      become: yes
      community.general.snap:
        name: go
        state: present
        classic: yes
      tags: go

    - name: Add VAULT_ADDR export to .bashrc
      become: no
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export VAULT_ADDR="https://vault.ops.songsterr.com:8200"'
        state: present

    - name: Add NOMAD_ADDR export to .bashrc
      become: no
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export NOMAD_ADDR="https://a2.ops.songsterr.com:4646"'
        state: present

    - name: Add NOMAD_CACERT export to .bashrc
      become: no
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export NOMAD_CACERT="$HOME/nomad/cachain.pem"'
        state: present

    - name: Add NOMAD_CLIENT_CERT export to .bashrc
      become: no
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export NOMAD_CLIENT_CERT="$HOME/nomad/cert.pem"'
        state: present

    - name: Add NOMAD_CLIENT_KEY export to .bashrc
      become: no
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export NOMAD_CLIENT_KEY="$HOME/nomad/privkey.pem"'
        state: present

    - name: Install Claude Code CLI
      ansible.builtin.command: npm install -g @anthropic-ai/claude-code
      become: yes
      args:
        creates: "/usr/local/bin/claude"
      environment:
        PATH: "{{ ansible_env.PATH }}"


