---
galaxy_info:
  author: "Setup Ubuntu"
  description: "Installs Cursor IDE AppImage with launcher"
  company: ""
  license: "MIT"
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - cursor
    - ide
    - editor
    - appimage 