---
galaxy_info:
  author: "Setup Ubuntu"
  description: "Installs outline-cli VPN client"
  company: ""
  license: "MIT"
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - vpn
    - outline
    - cli 